In [1]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [ ]:
scalar = tf.constant(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
vector = tf.constant([10,10])
vector

In [ ]:
vector.ndim

In [ ]:
matrix=tf.constant([[1,0],
                  [0,1]])
matrix

In [ ]:
matrix.ndim

In [ ]:
another_matrix=tf.constant([[1.,0.],
                           [0.,0.],
                           [0.,1.]],dtype=tf.float16)
another_matrix

In [ ]:
another_matrix.ndim

In [ ]:
tensor=tf.constant([[[1,1,1],
                    [1,1,1]],
                   [[1,1,1],
                   [1,1,1]],
                   [[1,1,1],
                   [1,1,1]]])
tensor

In [ ]:
tensor.ndim

In [ ]:
tf.Variable

In [ ]:
changeable_tensor=tf.Variable([10,7])
unchangebale_tensor=tf.constant([10,7])
changeable_tensor,unchangebale_tensor

In [ ]:
changeable_tensor[0]

In [ ]:
changeable_tensor.assign([5,3])

In [ ]:
changeable_tensor[0].assign(10)

In [ ]:
changeable_tensor

In [ ]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_1

In [ ]:
not_shffled=tf.constant([[1,0],
                         [0,0],
                         [0,1]]
                    )

In [ ]:
tf.random.shuffle(not_shffled)

In [ ]:
tf.ones([4,2])

In [ ]:
tf.zeros([1,1])

In [2]:
import numpy as np

In [ ]:
numpy_A=np.arange(1,25,dtype=np.int8)
numpy_A

In [ ]:
tensor_4_rank=tf.zeros(shape=(3,5,2,5))
tensor_4_rank

In [ ]:
for dim_1 in tensor_4_rank:
    for dim_2 in dim_1:
        for dim_3 in dim_2:
            print(dim_3[0])
            print(dim_3[1])

In [ ]:
tensor_4_rank[:2,:2,:2,:2]

In [ ]:
random_random_random=tf.constant(np.random.randint(0,100,size=50))

In [ ]:
tf.size(random_random_random), random_random_random.shape, random_random_random.ndim

In [ ]:
tf.reduce_min(random_random_random)

In [ ]:
tf.reduce_max(random_random_random)

In [ ]:
tf.reduce_mean(random_random_random)

In [ ]:
tf.reduce_sum(random_random_random)

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(random_random_random)

In [ ]:
tf.math.reduce_std(tf.cast(random_random_random,dtype=tf.float16))

In [3]:
random_random_random=tf.random.uniform(shape=[100])

In [4]:
random_random_random[tf.argmax(random_random_random)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9961109>

In [7]:
one_hot_list=[1,2,3]

In [13]:
tf.one_hot(one_hot_list,depth=3,dtype=tf.int8)

<tf.Tensor: shape=(3, 3), dtype=int8, numpy=
array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int8)>